"""empty message

Revision ID: 76491d3de163
Revises: 4148773b0934
Create Date: 2022-10-24 01:53:03.797376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76491d3de163'
down_revision = '4148773b0934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_project', sa.Column('filename_preferred', sa.String(length=255), nullable=True))
    op.add_column('ml_project', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_project', 'status')
    op.drop_column('ml_project', 'filename_preferred')
    # ### end Alembic commands ###
