"""empty message

Revision ID: 99e2700632af
Revises: 76491d3de163
Create Date: 2022-10-24 02:36:06.697164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e2700632af'
down_revision = '76491d3de163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('designation', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'designation')
    # ### end Alembic commands ###
